version: '3'
services:
  mariadb: 
    build: requirements/mariadb
    volumes:
      - mdb_vol:/var/lib/mysql
    networks:
      dockern:
        ipv4_address: 10.0.0.2
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: on-failure
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/usr/share/wordpress
    depends_on:
      -  "mariadb"
    networks:
      dockern:
        ipv4_address: 10.0.0.3
    restart: on-failure
  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress_vol:/usr/share/wordpress
    networks:
      dockern:
        ipv4_address: 10.0.0.4
    restart: on-failure
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - HOST_NAME=${HOST_NAME}
      - HTTP_HOST=${HOST_NAME}
    depends_on:
      - mariadb
volumes:
  mdb_vol: {}
  wordpress_vol: {}
networks:
  dockern: 
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1

  
